"""init finance table

Revision ID: 61488e8153ea
Revises: 72389014ff9d
Create Date: 2026-07-24 15:20:18.141596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '61488e8153ea'
down_revision: Union[str, Sequence[str], None] = '72389014ff9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 枚举类型在 PostgreSQL 里是独立的数据库类型，多张表共用同一个枚举时
    # 只能创建一次，否则第二张表会报 "type financedirection already exists"。
    # 用 postgresql.ENUM 并 create_type=False（这个参数只有 PG 方言认），
    # 手动 create 一次；三张表复用同一个 enum 对象。
    financedirection = postgresql.ENUM(
        'income', 'expense', name='financedirection', create_type=False
    )
    financedirection.create(op.get_bind(), checkfirst=True)

    op.create_table('finance_record',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('direction', financedirection, nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_by_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_treasurer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_receipt',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('direction', financedirection, nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('single_record',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('direction', financedirection, nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('invoice_receipt_id', sa.Uuid(), nullable=True),
    sa.Column('finance_record_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['finance_record_id'], ['finance_record.id'], ),
    sa.ForeignKeyConstraint(['invoice_receipt_id'], ['invoice_receipt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('single_record')
    op.drop_table('invoice_receipt')
    op.drop_table('finance_record')
    # 表全部删掉后再删枚举类型，否则类型还被列引用着删不掉
    sa.Enum(name='financedirection').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
