"""add bar_manager and tea_manager to permission enum

Revision ID: 70673b2e2593
Revises: efff7fea5799
Create Date: 2026-07-17 09:30:49.414737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '70673b2e2593'
down_revision: Union[str, Sequence[str], None] = 'efff7fea5799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Alembic autogenerate 不检测枚举变化，需要手写
    # PostgreSQL 枚举类型添加新值（IF NOT EXISTS 避免重复运行报错）
    op.execute("ALTER TYPE permission ADD VALUE IF NOT EXISTS 'bar_manager'")
    op.execute("ALTER TYPE permission ADD VALUE IF NOT EXISTS 'tea_manager'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
