"""add finance_manager permission

Revision ID: 72389014ff9d
Revises: f3fca0d35e89
Create Date: 2026-07-23 17:10:59.425180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '72389014ff9d'
down_revision: Union[str, Sequence[str], None] = 'f3fca0d35e89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 手动添加：向 permission 枚举类型添加新值 'finance_manager'
    op.execute("ALTER TYPE permission ADD VALUE 'finance_manager'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
