"""update whitelist

Revision ID: efff7fea5799
Revises: de43d891bb82
Create Date: 2026-07-15 09:57:17.021576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'efff7fea5799'
down_revision: Union[str, Sequence[str], None] = 'de43d891bb82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 添加 created_at 字段（分三步：先允许 NULL，填充默认值，再改为 NOT NULL）
    op.add_column('white_list', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE white_list SET created_at = NOW() WHERE created_at IS NULL")
    op.alter_column('white_list', 'created_at', nullable=False)

    # 添加可为空的字段（直接添加）
    op.add_column('white_list', sa.Column('retired_at', sa.DateTime(), nullable=True))
    op.add_column('white_list', sa.Column('retired_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # 添加 highest_permission 字段（复用已有的 permission 枚举类型）
    # 注意：不需要创建新的枚举类型，因为 permission 枚举已经存在
    op.execute("""
        ALTER TABLE white_list
        ADD COLUMN highest_permission permission
    """)
    op.execute("UPDATE white_list SET highest_permission = permission WHERE highest_permission IS NULL")
    op.execute("ALTER TABLE white_list ALTER COLUMN highest_permission SET NOT NULL")

    # 删除旧字段
    op.drop_column('white_list', 'working_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('white_list', sa.Column('working_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('white_list', 'highest_permission')
    op.drop_column('white_list', 'retired_description')
    op.drop_column('white_list', 'retired_at')
    op.drop_column('white_list', 'created_at')
    # ### end Alembic commands ###
