"""init all tables

Revision ID: f3fca0d35e89
Revises: 
Create Date: 2026-07-20 18:00:00.176606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f3fca0d35e89'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handover_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('to_user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_permission', sa.Enum('superadmin', 'president', 'vice_president', 'cocktail_minister', 'tea_minister', 'treasurer', 'tea_manager', 'bar_manager', name='permission'), nullable=False),
    sa.Column('self_permission', sa.Enum('superadmin', 'president', 'vice_president', 'cocktail_minister', 'tea_minister', 'treasurer', 'tea_manager', 'bar_manager', name='permission'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'cancelled', name='status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_handover_table_token'), 'handover_table', ['token'], unique=True)
    op.create_table('white_list',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('permission', sa.Enum('superadmin', 'president', 'vice_president', 'cocktail_minister', 'tea_minister', 'treasurer', 'tea_manager', 'bar_manager', name='permission'), nullable=False),
    sa.Column('wechat_account', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('retired', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('highest_permission', sa.Enum('superadmin', 'president', 'vice_president', 'cocktail_minister', 'tea_minister', 'treasurer', 'tea_manager', 'bar_manager', name='permission'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_white_list_email'), 'white_list', ['email'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('whitelist_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['whitelist_id'], ['white_list.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix_white_list_email'), table_name='white_list')
    op.drop_table('white_list')
    op.drop_index(op.f('ix_handover_table_token'), table_name='handover_table')
    op.drop_table('handover_table')
    # ### end Alembic commands ###
